### ISSUE TITLE
同参数情况下，单卡正常运行，多卡DDP显存OOM

### ISSUE THREAD

**Issue by yangzhch6** [modelscope/ms-swift#2293]
## **Describe the bug**
同参数情况下微调，单卡正常运行，多卡OOM。

单卡微调sh:
```
CUDA_VISIBLE_DEVICES=0 swift sft \
    --dtype bf16 \
    --template_type AUTO \
    --model_type llama3-8b-instruct \
    --model_id_or_path /... \
    --dataset /... \
    --val_dataset /... \
    --output_dir /... \
    --sft_type "full" \
    --learning_rate 1e-5 \
    --weight_decay 0.1 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --batch_size 2 \
    --gradient_accumulation_steps 16 \
    --max_length 4096 \
    --num_train_epochs 3 \
    --save_strategy "epoch" \
    --save_total_limit 3 \
```

两卡微调sh:
```
CUDA_VISIBLE_DEVICES=0,1 \
NPROC_PER_NODE=2 \
swift sft \
    --dtype bf16 \
    --template_type AUTO \
    --model_type llama3-8b-instruct \
    --model_id_or_path /... \
    --dataset /... \
    --val_dataset /... \
    --output_dir /... \
    --sft_type "full" \
    --learning_rate 1e-5 \
    --weight_decay 0.1 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --batch_size 1 \
    --gradient_accumulation_steps 16 \
    --max_length 4096 \
    --num_train_epochs 3 \
    --save_strategy "epoch" \
    --save_total_limit 3 \
```
即便加上了 `--deepspeed 'default-zero2' ` 依旧爆显存。
按理说单卡batchsize为2不爆显存，那么多卡ddp场景batchsize=1也不会爆，很奇怪的问题

## **hardware and system info**
CUDA 11.8
GPU：A800, 80G
torch 2.4.0
Linux

**Comment by yangzhch6** [comment]
补充一些额外信息：
用上述单卡微调sh，同数据集耗时1h45min：
```
CUDA_VISIBLE_DEVICES=0 swift sft \
    --dtype bf16 \
    --template_type AUTO \
    --model_type llama3-8b-instruct \
    --model_id_or_path /... \
    --dataset /... \
    --val_dataset /... \
    --output_dir /... \
    --sft_type "full" \
    --learning_rate 1e-5 \
    --weight_decay 0.1 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --batch_size 2 \
    --gradient_accumulation_steps 16 \
    --max_length 4096 \
    --num_train_epochs 3 \
    --save_strategy "epoch" \
    --save_total_limit 3 \
```

我更改成双卡微调加上后zero3后，同一个数据集预计耗时20h
```
CUDA_VISIBLE_DEVICES=0,1 \
NPROC_PER_NODE=2 \
swift sft \
    --dtype bf16 \
    --template_type AUTO \
    --model_type llama3-8b-instruct \
    --model_id_or_path /... \
    --dataset /... \
    --val_dataset /... \
    --output_dir /... \
    --sft_type "full" \
    --learning_rate 1e-5 \
    --weight_decay 0.1 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --batch_size 1 \
    --gradient_accumulation_steps 16 \
    --max_length 4096 \
    --num_train_epochs 3 \
    --save_strategy "epoch" \
    --save_total_limit 3 \
    --deepspeed 'default-zero3'
```

**Comment by yangzhch6** [comment]
对比torch tune微调llama3-8b，torchtune能跑起来，yaml配置如下

```
# Config for multi-device full finetuning in full_finetune_distributed.py
# using a Llama3 8B Instruct model
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download meta-llama/Meta-Llama-3-8B-Instruct --output-dir /hpc2hdd/home/zyang398/yangzhch6/models/LLM-Research/Meta-Llama-3-8B-Instruct --hf-token <HF_TOKEN>
#
# To launch on 4 devices, run the following command from root:
#   tune run --nproc_per_node 4 full_finetune_distributed --config llama3/8B_full
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training
# you can run:
#   tune run --nproc_per_node 4 full_finetune_distributed --config llama3/8B_full checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works best when the model is being fine-tuned on 2+ GPUs.
# Single device full finetuning requires more memory optimizations. It's
# best to use 8B_full_single_device.yaml for those cases


# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /hpc2hdd/home/zyang398/yangzhch6/models/LLM-Research/Meta-Llama-3-8B-Instruct/original/tokenizer.model
  max_seq_len: null

# Dataset
dataset:
  _component_: torchtune.datasets.alpaca_dataset
seed: null
shuffle: True

# Model Arguments
model:
  _component_: torchtune.models.llama3.llama3_8b

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /hpc2hdd/home/zyang398/yangzhch6/models/LLM-Research/Meta-Llama-3-8B-Instruct/
  checkpoint_files: [
    model-00001-of-00004.safetensors,
    model-00002-of-00004.safetensors,
    model-00003-of-00004.safetensors,
    model-00004-of-00004.safetensors
  ]
  recipe_checkpoint: null
  output_dir: tmp/
  model_type: LLAMA3
resume_from_checkpoint: False

# Fine-tuning arguments
batch_size: 2
epochs: 3

optimizer:
  _component_: torch.optim.AdamW
  lr: 2e-5
  fused: True
loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss
max_steps_per_epoch: null
gradient_accumulation_steps: 1


# Training env
device: cuda

# Memory management
enable_activation_checkpointing: True
custom_sharded_layers: ['tok_embeddings', 'output']

# Reduced precision
dtype: bf16

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: ${output_dir}
output_dir: /tmp/full-llama3-finetune
log_every_n_steps: 1
log_peak_memory_stats: False
```

虽然数据集暂未设置成一致，但我认为这说明swift的DDP训练可能存在bug。

>希望你们能解决这个问题，感谢了
